const DEFAULT_PRODUCTS=[
{id:'p1',name:'Fresh Marigold Flowers',category:'flowers',price:50,stock:25,image:'',description:'Fresh puja flowers for daily devotion.'},
{id:'p2',name:'Daily Puja Kit',category:'kits',price:149,stock:18,image:'',description:'Essential items for your daily puja.'},
{id:'p3',name:'Dhoop Sticks',category:'essentials',price:80,stock:30,image:'',description:'Fragrant dhoop for your prayer space.'},
{id:'p4',name:'Brass Diya',category:'essentials',price:120,stock:12,image:'',description:'Traditional brass diya for your mandir.'},
{id:'p5',name:'Hanuman Ji Puja Kit',category:'kits',price:199,stock:10,image:'',description:'Curated Tuesday Hanuman Ji puja kit.'},
{id:'p6',name:'Brass Ganesh Ji Idol',category:'idols',price:699,stock:7,image:'',description:'Elegant brass idol, suitable for home mandir.'}
];
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const read=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let products=read('arpan_products',DEFAULT_PRODUCTS),cart=read('arpan_cart',[]),locationData=null;
const $=s=>document.querySelector(s);
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function render(){const q=($('#search')?.value||'').toLowerCase(),cat=$('#category')?.value||'all';const list=products.filter(p=>(cat==='all'||p.category===cat)&&p.name.toLowerCase().includes(q));$('#productGrid').innerHTML=list.map(p=>`<article class="product"><div class="product-img">${p.image?`<img src="${p.image}" alt="${esc(p.name)}">`:'🪔'}</div><div class="muted">${esc(p.category)}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="product-row"><strong>${money(p.price)}</strong><span class="stock">${p.stock>0?`${p.stock} available`:'Out of stock'}</span></div><button class="btn primary full" ${p.stock<1?'disabled':''} onclick="addToCart('${p.id}')">Add to cart</button></article>`).join('')||'<p>No products found.</p>';updateCart();}
function addToCart(id){const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id);if(!p||p.stock<1)return;if(item){if(item.qty>=p.stock)return toast('Only '+p.stock+' available');item.qty++}else cart.push({id,qty:1});write('arpan_cart',cart);updateCart();toast('Added to cart')}
function updateCart(){const count=cart.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=count;const total=cart.reduce((s,x)=>{const p=products.find(p=>p.id===x.id);return s+(p?p.price*x.qty:0)},0);$('#cartTotal').textContent=money(total);$('#checkoutTotal').textContent=money(total);$('#cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-item"><div><b>${esc(p?.name)}</b><small>${money(p?.price)} each</small></div><div class="qty"><button onclick="changeQty('${x.id}',-1)">−</button><span>${x.qty}</span><button onclick="changeQty('${x.id}',1)">+</button></div></div>`}).join(''):'<p class="muted">Your cart is empty.</p>'}
function changeQty(id,d){const x=cart.find(i=>i.id===id),p=products.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);else if(x.qty>p.stock)x.qty=p.stock;write('arpan_cart',cart);updateCart()}
function openCart(){$('#drawer').classList.add('open');$('#overlay').classList.add('show');updateCart()};function closeCart(){$('#drawer').classList.remove('open');$('#overlay').classList.remove('show')}
function locate(){if(!navigator.geolocation)return toast('Geolocation is not supported');toast('Detecting your location…');navigator.geolocation.getCurrentPosition(pos=>{locationData={lat:pos.coords.latitude,lng:pos.coords.longitude};const text=`${locationData.lat.toFixed(6)}, ${locationData.lng.toFixed(6)}`;$('#locationStatus').textContent='Location detected: '+text;$('#checkoutLocation').textContent=text;$('#map').classList.remove('hidden');$('#map').innerHTML=`<iframe loading="lazy" src="https://www.google.com/maps?q=${locationData.lat},${locationData.lng}&z=16&output=embed"></iframe>`},()=>toast('Please allow location access in your browser'))}
function openCheckout(){if(!cart.length)return toast('Add products first');$('#checkout').classList.remove('hidden');updateCart()}
function placeOrder(){const name=$('#name').value.trim(),phone=$('#phone').value.trim(),address=$('#address').value.trim();if(!name||!phone||!address)return toast('Please fill all delivery details');const items=cart.map(x=>{const p=products.find(p=>p.id===x.id);return {id:p.id,name:p.name,price:p.price,qty:x.qty,total:p.price*x.qty}});const subtotal=items.reduce((s,x)=>s+x.total,0),delivery=subtotal>=499?0:30,total=subtotal+delivery;const order={id:'AC'+Date.now().toString().slice(-8),date:new Date().toISOString(),customer:{name,phone,address,location:locationData},items,subtotal,delivery,total,status:'New',payment:'Cash on Delivery'};const orders=read('arpan_orders',[]);orders.unshift(order);write('arpan_orders',orders);products=products.map(p=>{const i=items.find(x=>x.id===p.id);return i?{...p,stock:p.stock-i.qty}:p});write('arpan_products',products);cart=[];write('arpan_cart',cart);$('#checkout').classList.add('hidden');closeCart();render();toast('Order '+order.id+' placed successfully')}
$('#search').addEventListener('input',render);$('#category').addEventListener('change',render);$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeCart;$('#overlay').onclick=closeCart;$('#checkoutBtn').onclick=openCheckout;$('#closeCheckout').onclick=()=>$('#checkout').classList.add('hidden');$('#locateBtn').onclick=locate;$('#detectCheckout').onclick=locate;$('#placeOrder').onclick=placeOrder;render();
