let D={}, cart=JSON.parse(localStorage.getItem('arpanCart')||'[]');
const $=s=>document.querySelector(s); const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
async function api(url,opt={}){let r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});return r.json()}
async function load(){D=await api('/api/data'); renderShop(); updateCart()}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',1800)}
function renderShop(){let cats=D.categories.filter(x=>x.active); $('#app').innerHTML=`<section class="hero"><div><h1>Everything you need, thoughtfully delivered.</h1><p>Welcome to ArpanCart — your modern destination for puja samagri, household essentials and curated packs.</p><button class="btn" onclick="document.querySelector('#products').scrollIntoView()">Shop now</button></div><div class="pic" style="width:300px;height:220px">🛍️</div></section><div class="container"><div class="row" style="justify-content:space-between"><h2 id="products">Featured products</h2><input class="input" id="search" style="max-width:300px" placeholder="Search products..." oninput="filterProducts()"></div><div class="grid" id="productGrid"></div></div>`; drawProducts(D.products)}
function drawProducts(items){$('#productGrid').innerHTML=items.filter(p=>p.active).map(p=>`<article class="card"><div class="pic">🪔</div><div class="muted">${catName(p.category_id)}</div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.description||'')}</p><div class="price">${money(p.price)}</div><button class="btn" onclick="addCart('${p.id}')">Add to cart</button></article>`).join('')||'<p>No products found.</p>'}
function filterProducts(){let q=$('#search').value.toLowerCase();drawProducts(D.products.filter(p=>p.name.toLowerCase().includes(q)))}
function catName(id){return (D.categories.find(c=>c.id===id)||{}).name||'General'}
function addCart(id){let p=D.products.find(x=>x.id===id);let q=cart.find(x=>x.id===id);q?q.qty++:cart.push({id,qty:1});localStorage.setItem('arpanCart',JSON.stringify(cart));updateCart();toast('Added to cart')}
function updateCart(){$('#cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0)}
function showCart(){let total=cart.reduce((s,x)=>s+(D.products.find(p=>p.id===x.id)?.price||0)*x.qty,0);$('#app').innerHTML=`<div class="container"><h2>Your Cart</h2>${cart.map(x=>{let p=D.products.find(p=>p.id===x.id);return `<div class="panel row" style="justify-content:space-between;margin:8px 0"><div><b>${p?.name}</b><div>${money(p?.price)} × ${x.qty}</div></div><button class="btn alt" onclick="removeCart('${x.id}')">Remove</button></div>`}).join('')||'<p>Your cart is empty.</p>'}<h2>Total: ${money(total)}</h2>${cart.length?`<div class="panel form"><input class="input" id="cname" placeholder="Full name"><input class="input" id="cphone" placeholder="Phone"><input class="input" id="caddr" placeholder="Delivery address"><select class="input" id="pay"><option>Cash on Delivery</option><option>Online Payment (demo)</option></select><button class="btn" onclick="placeOrder()">Place order</button></div>`:''}</div>`}
function removeCart(id){cart=cart.filter(x=>x.id!==id);localStorage.setItem('arpanCart',JSON.stringify(cart));showCart();updateCart()}
async function placeOrder(){let items=cart.map(x=>{let p=D.products.find(p=>p.id===x.id);return {product_id:x.id,name:p.name,price:p.price,qty:x.qty}});let total=items.reduce((s,x)=>s+x.price*x.qty,0);let r=await api('/api/orders',{method:'POST',body:JSON.stringify({customer:{name:$('#cname').value,phone:$('#cphone').value,address:$('#caddr').value},items,total,payment:$('#pay').value})});if(r.ok){cart=[];localStorage.removeItem('arpanCart');await load();toast('Order placed successfully')}}
function renderServices(){let s=D.services;$('#app').innerHTML=`<div class="container"><h2>Service Menu</h2><p class="muted">Browse ArpanCart services.</p><div class="grid">${s.map(x=>`<div class="card"><div class="muted">${esc(x.category)}</div><h3>${esc(x.name)}</h3><div class="price">${money(x.price)}</div></div>`).join('')||'<p>No services yet. Admin can import them from CSV.</p>'}</div></div>`}
function renderAdmin(){let revenue=D.orders.reduce((s,o)=>s+Number(o.total||0),0);$('#app').innerHTML=`<div class="container"><h2>ArpanCart Admin</h2><div class="statgrid"><div class="stat">Products<strong>${D.products.length}</strong></div><div class="stat">Services<strong>${D.services.length}</strong></div><div class="stat">Orders<strong>${D.orders.length}</strong></div><div class="stat">Revenue<strong>${money(revenue)}</strong></div></div><div class="adminnav" style="margin-top:25px"><button onclick="adminProducts()">Products</button><button onclick="adminServices()">Service Menu Database</button><button onclick="adminOrders()">Orders</button><button onclick="backup()">Create Backup</button></div><div id="adminPanel"></div></div>`;adminProducts()}
function adminProducts(){$('#adminPanel').innerHTML=`<div class="panel"><h3>Add Product</h3><div class="form"><input class="input" id="pn" placeholder="Product name"><select class="input" id="pc">${D.categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select><input class="input" id="pp" type="number" placeholder="Price"><input class="input" id="ps" type="number" placeholder="Stock"><textarea class="input" id="pd" placeholder="Description"></textarea><button class="btn" onclick="addProduct()">Save product</button></div><h3>Products</h3><table class="table"><tr><th>Name</th><th>Price</th><th>Stock</th><th></th></tr>${D.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="btn alt" onclick="del('products','${p.id}')">Delete</button></td></tr>`).join('')}</table></div>`}
async function addProduct(){await api('/api/products',{method:'POST',body:JSON.stringify({name:$('#pn').value,category_id:$('#pc').value,price:$('#pp').value,stock:$('#ps').value,description:$('#pd').value})});D=await api('/api/data');adminProducts();toast('Product saved')}
function adminServices(){$('#adminPanel').innerHTML=`<div class="panel"><h3>Service Menu Database</h3><p class="muted">Import a CSV with columns: <b>name,category,price,active</b>.</p><div class="row"><input id="csvfile" type="file" accept=".csv" class="input"><button class="btn" onclick="importCSV()">Import CSV</button><button class="btn alt" onclick="exportServices()">Export CSV</button></div><hr><div class="form"><input class="input" id="sn" placeholder="Service name"><input class="input" id="sc" placeholder="Category"><input class="input" id="sp" type="number" placeholder="Price"><button class="btn" onclick="addService()">Add service</button></div><table class="table" style="margin-top:20px"><tr><th>Service</th><th>Category</th><th>Price</th><th></th></tr>${D.services.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.category)}</td><td>${money(s.price)}</td><td><button class="btn alt" onclick="del('services','${s.id}')">Delete</button></td></tr>`).join('')}</table></div>`}
async function importCSV(){let f=$('#csvfile').files[0];if(!f)return toast('Select a CSV file');let csv=await f.text();let r=await api('/api/services/import',{method:'POST',body:JSON.stringify({csv})});D=await api('/api/data');adminServices();toast(`Imported ${r.result?.added||0} services`)}
async function addService(){await api('/api/services',{method:'POST',body:JSON.stringify({name:$('#sn').value,category:$('#sc').value,price:$('#sp').value})});D=await api('/api/data');adminServices();toast('Service saved')}
function exportServices(){let csv='name,category,price,active\n'+D.services.map(s=>`"${s.name.replaceAll('"','""')}","${s.category}",${s.price},${s.active}`).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='arpancart-services.csv';a.click()}
function adminOrders(){$('#adminPanel').innerHTML=`<div class="panel"><h3>Orders</h3><table class="table"><tr><th>ID</th><th>Customer</th><th>Total</th><th>Status</th></tr>${D.orders.map(o=>`<tr><td>${o.id.slice(-8)}</td><td>${esc(o.customer?.name||'')}</td><td>${money(o.total)}</td><td>${o.status}</td></tr>`).join('')||'<tr><td colspan="4">No orders yet.</td></tr>'}</table></div>`}
async function backup(){let r=await api('/api/backup');toast('Backup created: '+r.file);window.open('/backups/'+r.file,'_blank')}
async function del(c,id){if(!confirm('Delete this item?'))return;await api('/api/delete',{method:'DELETE',body:JSON.stringify({collection:c,id})});D=await api('/api/data');c==='products'?adminProducts():adminServices()}
function esc(x){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
document.addEventListener('click',e=>{let v=e.target.dataset.view;if(v==='shop')renderShop();if(v==='services')renderServices();if(v==='admin')renderAdmin();if(e.target.id==='cartBtn')showCart()});load();
