import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import pg from 'pg';

const { Pool } = pg;
const pool = new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const app=express();
app.use(cors());
app.use(express.json({limit:'2mb'}));
const sign=a=>jwt.sign({sub:a.id,role:'admin',email:a.email},process.env.JWT_SECRET,{expiresIn:'12h'});
function auth(req,res,next){try{const h=req.headers.authorization||'';req.user=jwt.verify(h.startsWith('Bearer ')?h.slice(7):'',process.env.JWT_SECRET);next()}catch{res.status(401).json({error:'Unauthorized'})}}
const slug=s=>String(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

app.get('/api/health',(req,res)=>res.json({ok:true,service:'arpancart-api'}));
app.post('/api/auth/login',async(req,res)=>{const {email,password}=req.body;const {rows}=await pool.query('select * from admins where email=$1',[email]);if(!rows[0]||!(await bcrypt.compare(password,rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'});res.json({token:sign(rows[0]),admin:{id:rows[0].id,email:rows[0].email}})});
app.get('/api/products',async(req,res)=>{const {rows}=await pool.query('select * from products where active=true order by created_at desc');res.json(rows)});
app.post('/api/products',auth,async(req,res)=>{const {name,category='essentials',description='',image_url='',price=0,stock=0,active=true}=req.body;const {rows}=await pool.query('insert into products(name,slug,category,description,image_url,price,stock,active) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[name,slug(name+'-'+Date.now()),category,description,image_url,price,stock,active]);res.status(201).json(rows[0])});
app.patch('/api/products/:id',auth,async(req,res)=>{const fields=['name','category','description','image_url','price','stock','active'],vals=[],sets=[];for(const f of fields)if(req.body[f]!==undefined){vals.push(req.body[f]);sets.push(`${f}=$${vals.length}`)}if(!sets.length)return res.status(400).json({error:'Nothing to update'});vals.push(req.params.id);const {rows}=await pool.query(`update products set ${sets.join(',')},updated_at=now() where id=$${vals.length} returning *`,vals);res.json(rows[0])});
app.get('/api/dashboard',auth,async(req,res)=>{const [o,c,p,r,l,rf,w]=await Promise.all([pool.query("select count(*)::int count from orders where created_at>=date_trunc('month',now())"),pool.query('select count(*)::int count from customers'),pool.query('select count(*)::int count from products where active=true'),pool.query("select coalesce(sum(total),0) total from orders where payment_status='paid'"),pool.query('select count(*)::int count from products where active=true and stock<=5'),pool.query('select count(*)::int count from referrals'),pool.query("select coalesce(sum(amount),0) total from wallet_transactions where type='credit'")]);res.json({orders:o.rows[0].count,customers:c.rows[0].count,products:p.rows[0].count,revenue:r.rows[0].total,lowStock:l.rows[0].count,referrals:rf.rows[0].count,walletCredits:w.rows[0].total})});
app.get('/api/crm/customers',auth,async(req,res)=>{const {rows}=await pool.query(`select c.*,count(o.id)::int orders,coalesce(sum(o.total),0) lifetime_value from customers c left join orders o on o.customer_id=c.id group by c.id order by c.created_at desc`);res.json(rows)});
app.post('/api/crm/customers/:id/notes',auth,async(req,res)=>{const {rows}=await pool.query('insert into crm_notes(customer_id,note,next_follow_up) values($1,$2,$3) returning *',[req.params.id,req.body.note,req.body.next_follow_up||null]);res.status(201).json(rows[0])});
app.get('/api/crm/customers/:id/notes',auth,async(req,res)=>{const {rows}=await pool.query('select * from crm_notes where customer_id=$1 order by created_at desc',[req.params.id]);res.json(rows)});
app.get('/api/referrals',auth,async(req,res)=>{const {rows}=await pool.query(`select r.*,a.name referrer_name,b.name referred_name from referrals r join customers a on a.id=r.referrer_customer_id left join customers b on b.id=r.referred_customer_id order by r.created_at desc`);res.json(rows)});
app.post('/api/referrals/:id/reward',auth,async(req,res)=>{const client=await pool.connect();try{await client.query('begin');const {rows}=await client.query('select * from referrals where id=$1 for update',[req.params.id]);const r=rows[0];if(!r||r.status==='rewarded')throw Error('Referral already rewarded or missing');await client.query('update customers set wallet_balance=wallet_balance+$1,updated_at=now() where id=$2',[r.reward_amount,r.referrer_customer_id]);await client.query("insert into wallet_transactions(customer_id,type,amount,reason,reference) values($1,'credit',$2,'Referral reward',$3)",[r.referrer_customer_id,r.reward_amount,r.id]);await client.query("update referrals set status='rewarded' where id=$1",[r.id]);await client.query('commit');res.json({ok:true})}catch(e){await client.query('rollback');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/wallet',auth,async(req,res)=>{const {rows}=await pool.query('select w.*,c.name,c.phone from wallet_transactions w join customers c on c.id=w.customer_id order by w.created_at desc limit 200');res.json(rows)});
app.post('/api/wallet/adjust',auth,async(req,res)=>{const {customer_id,type,amount,reason}=req.body;if(!['credit','debit'].includes(type)||Number(amount)<=0)return res.status(400).json({error:'Invalid wallet adjustment'});const client=await pool.connect();try{await client.query('begin');if(type==='debit'){const q=await client.query('select wallet_balance from customers where id=$1 for update',[customer_id]);if(!q.rows[0]||Number(q.rows[0].wallet_balance)<Number(amount))throw Error('Insufficient wallet balance')}const delta=type==='credit'?amount:-amount;await client.query('update customers set wallet_balance=wallet_balance+$1,updated_at=now() where id=$2',[delta,customer_id]);const {rows}=await client.query('insert into wallet_transactions(customer_id,type,amount,reason) values($1,$2,$3,$4) returning *',[customer_id,type,amount,reason]);await client.query('commit');res.status(201).json(rows[0])}catch(e){await client.query('rollback');res.status(400).json({error:e.message})}finally{client.release()}});
app.get('/api/orders',auth,async(req,res)=>{const {rows}=await pool.query('select o.*,c.name,c.phone,c.email from orders o left join customers c on c.id=o.customer_id order by o.created_at desc limit 200');res.json(rows)});
app.patch('/api/orders/:id/status',auth,async(req,res)=>{const {rows}=await pool.query('update orders set status=$1,updated_at=now() where id=$2 returning *',[req.body.status,req.params.id]);res.json(rows[0])});
app.post('/api/billing',auth,async(req,res)=>{const {customer,items,payment_method='cash',delivery_fee=0}=req.body;if(!items?.length)return res.status(400).json({error:'No items'});const client=await pool.connect();try{await client.query('begin');let customerId=null;if(customer?.phone){const q=await client.query(`insert into customers(name,phone,email,address) values($1,$2,$3,$4) on conflict(phone) do update set name=excluded.name,email=excluded.email,address=excluded.address,updated_at=now() returning id`,[customer.name,customer.phone,customer.email||null,customer.address||null]);customerId=q.rows[0].id}let subtotal=0;const locked=[];for(const i of items){const q=await client.query('select id,name,price,stock from products where id=$1 for update',[i.product_id]);if(!q.rows[0]||q.rows[0].stock<i.quantity)throw Error('Insufficient stock');subtotal+=Number(q.rows[0].price)*Number(i.quantity);locked.push({i,p:q.rows[0]})}const total=subtotal+Number(delivery_fee),orderNo='AC-'+Date.now().toString().slice(-8);const oq=await client.query(`insert into orders(order_number,customer_id,status,payment_method,subtotal,delivery_fee,total) values($1,$2,'new',$3,$4,$5,$6) returning *`,[orderNo,customerId,payment_method,subtotal,delivery_fee,total]);for(const {i,p} of locked){await client.query('update products set stock=stock-$1,updated_at=now() where id=$2',[i.quantity,p.id]);await client.query('insert into order_items(order_id,product_id,product_name,unit_price,quantity,line_total) values($1,$2,$3,$4,$5,$6)',[oq.rows[0].id,p.id,p.name,p.price,i.quantity,Number(p.price)*i.quantity])}await client.query('commit');res.status(201).json(oq.rows[0])}catch(e){await client.query('rollback');res.status(400).json({error:e.message})}finally{client.release()}});

app.post('/api/payments/razorpay/order',async(req,res)=>{try{if(!process.env.RAZORPAY_KEY_ID||!process.env.RAZORPAY_KEY_SECRET)return res.status(503).json({error:'Razorpay is not configured'});const {amount,receipt,notes={}}=req.body;if(!Number(amount)||Number(amount)<=0)return res.status(400).json({error:'Invalid amount'});const authHeader=Buffer.from(`${process.env.RAZORPAY_KEY_ID}:${process.env.RAZORPAY_KEY_SECRET}`).toString('base64');const r=await fetch('https://api.razorpay.com/v1/orders',{method:'POST',headers:{Authorization:`Basic ${authHeader}`,'Content-Type':'application/json'},body:JSON.stringify({amount:Math.round(Number(amount)*100),currency:'INR',receipt:receipt||`rcpt_${Date.now()}`,notes,capture:'automatic'})});const data=await r.json();res.status(r.ok?200:r.status).json(data)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/payments/razorpay/verify',async(req,res)=>{try{const {razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body;const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest('hex');const a=Buffer.from(expected),b=Buffer.from(razorpay_signature||'');if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(400).json({error:'Invalid payment signature'});res.json({verified:true,payment_id:razorpay_payment_id})}catch(e){res.status(400).json({error:'Payment verification failed'})}});

export default app;
